config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'home/index'
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:item_name, :quantity, :cost, :shelf_life_in_days)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'RonR Inventory Management', root_path, class:"navbar-brand" %>
  <div class="container-fluid">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'About', home_about_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Products', products_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add Product', new_product_path, class:"nav-link active" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Page</h1>

<P> Thanks for coming by! This app is still in progress utilizing a Ruby on Rails stack. The final goal of this app is to manage inventory and update it with each purchase. For example, if someone bought a BLT, the expected inventory for bread, mayo, bacon, lettuce, tomato would all be updated concurrently in the store's inventory. This will query and create an expected inventory report when needed that the client (restaurant/grocery) can compare. Seeing the actual inventory vs expected inventory can help a store find deeper clarity on where they're coming up short in procedures or meeting standards. This also benefits the store in assessing the urgency of improvements needed in cost reduction, helping prioritize which issues are hurting the company most and which strengths are setting their venue apart. </P>

<h3>
  You are able to create, read, update, and delete manually. Query-based inventory reductions (ordering) coming soon.
</h3>


<!--<button type="button" class="btn btn-info">Return to Home</button>-->

app/views/home/index.html.erb
<h1>Home Page</h1>
<p>Select an option above to begin system management.</p>

<!--<button type="button" class="btn btn-success">Place An Order</button>-->
<!--<button type="button" class="btn btn-warning">Manual Adjustments</button>-->

app/views/layouts/_alerts.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <title>Inventory About</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", media:'all', "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>

<%= render 'home/header' %>
<div class="container">
  <br/>
<% if notice %>
  <%= render 'layouts/alerts' %>
    <% end %>

<br/>
<%= yield %>
<!--<h3>Created by John Brooks</h3>-->
</div>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

</body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :item_name, style: "display: block" %>
    <%= form.text_field :item_name %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.text_field :quantity %>
  </div>

  <div>
    <%= form.label :cost, style: "display: block" %>
    <%= form.text_field :cost %>
  </div>

  <div>
    <%= form.label :shelf_life_in_days, style: "display: block" %>
    <%= form.number_field :shelf_life_in_days %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
  <tr>
    <th>Name</th>
    <th>Quantity</th>
    <th>Costs</th>
    <th>Shelf Life in Days</th>
    <th>Information</th>
  </tr>
  </thead>

  <tbody>
  <tr>
  <td><%= product.item_name %></td>
  <td><%= product.quantity %></td>
  <td><%= product.cost %></td>
  <td><%= product.shelf_life_in_days %></td>

    <td><%= link_to 'View', product, class: "btn btn-success btn-sm" %>

  </tr>
  </tbody>
  </table>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
  <% end %>
</div>
<%= link_to "New product", new_product_path, class: "btn btn-primary color-change" %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path, class: "btn btn-primary color-change" %>
</div>

app/views/products/show.html.erb
<%= render @product %>

<div>
   <%= link_to "Edit this product", edit_product_path(@product), class: "btn btn-warning color-change" %>
  <br/>
  <br/>
   <%= link_to "Back to product", products_path(@product), class: "btn btn-primary color-change" %>
  <br/>
  <br/>
  <%= button_to "Destroy this product", @product, method: :delete, class: "btn btn-danger color-change" %>
</div>